stages:
  - build
  - replay
  - test
  - cleanup

variables:
  # Variables required by Common CI jobs
  CI_COMMON_JOB_VERSION: "a3e97d90268154fae7933ea98e50e3c1c7c72d43"
  DOCKER_BUILDER_TAG: "$CI_COMMON_JOB_VERSION"
  DOCKER_DIND_TAG: "$CI_COMMON_JOB_VERSION"
  IMAGE_REMOVER_TAG: "$CI_COMMON_JOB_VERSION"

  # Git configuration
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive

  # Replay confioguration
  HIVE_API_NODE_VERSION: 1.27.5
  HAF_VERSION: ${HIVE_API_NODE_VERSION}rc9
  HIVEMIND_INSTANCE_VERSION: ${HIVE_API_NODE_VERSION}rc9
  HAFAH_VERSION: ${HIVE_API_NODE_VERSION}rc9
  BLOCK_LOG_SOURCE_DIR: "/blockchain/block_log_5m"
  REPLAY_DIRECTORY_PREFIX: "/cache/replay_data_haf_api_node"
  REPLAY_DIRECTORY: "${REPLAY_DIRECTORY_PREFIX}_${CI_COMMIT_SHORT_SHA}_${HAF_VERSION}_${HIVEMIND_INSTANCE_VERSION}_${HAFAH_VERSION}"
  REPLAY_PIPELINE_DIRECTORY: "${REPLAY_DIRECTORY_PREFIX}_${CI_PIPELINE_ID}"
  DOCKER_TLS_CERTDIR: "${REPLAY_PIPELINE_DIRECTORY}_certs"

include:
  - template: Workflows/Branch-Pipelines.gitlab-ci.yml
  - project: hive/common-ci-configuration
    ref: a3e97d90268154fae7933ea98e50e3c1c7c72d43
    file:
      - /templates/docker_image_jobs.gitlab-ci.yml
      - /templates/cache_cleanup.gitlab-ci.yml

######## Build ########

docker-build:
  extends: .docker_image_builder_job_template
  stage: build
  variables:
    TAG: "${CI_COMMIT_SHORT_SHA}"
  before_script:
    - !reference [.docker_image_builder_job_template, before_script]
    - |
      echo -e "\e[0Ksection_start:$(date +%s):login[collapsed=true]\r\e[0KLogging to Docker registry..."
      docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
      echo -e "\e[0Ksection_end:$(date +%s):login\r\e[0K"
  script:
    - |
      echo -e "\e[0Ksection_start:$(date +%s):build[collapsed=true]\r\e[0KBaking Docker images..."
      docker buildx bake --file=docker-bake.hcl --provenance=false --progress="plain" "ci"
      echo -e "\e[0Ksection_end:$(date +%s):build\r\e[0K"
  tags:
    - public-runner-docker
    - hived-for-tests

######## End build ########

######## Replay ########

haf-node-replay:
  extends: .job-defaults
  stage: replay
  timeout: 2 hours
  needs:
    - docker-build
  variables:
    TOP_LEVEL_DATASET_MOUNTPOINT: "${REPLAY_DIRECTORY}"
    LAST_BLOCK_NUMBER: "5000000"
    ARGUMENTS: "--plugin database_api --replay-blockchain --stop-at-block ${LAST_BLOCK_NUMBER}"
    PUBLIC_HOSTNAME: "docker"
    DOCKER_DRIVER: "overlay2"
    CI_DEBUG_SERVICES: "false" # Change to true to debug services in this job
    GIT_STRATEGY: "none"
    HAF_DB_URL: "postgresql://hivemind@haf/haf_block_log"
    PSQL_COMMAND: "SELECT current_block_num FROM hive.contexts WHERE name = 'hivemind_app'"
  image: 
    name: registry.gitlab.syncad.com/hive/haf_api_node/compose:${CI_COMMIT_SHORT_SHA}
    entrypoint: [ "" ]
  services:
    - name: registry.gitlab.syncad.com/hive/haf_api_node/dind:${CI_COMMIT_SHORT_SHA}
      alias: docker
  script:
   - |
     set -e
     
     echo -e "\e[0Ksection_start:$(date +%s):check[collapsed=true]\r\e[0KChecking replay status..."
     while [[ -f "${REPLAY_DIRECTORY}/replay_running" ]]; do
      echo "Another replay is running in $DATA_CACHE. Waiting for it to end..."
      sleep 60
     done
     if [[ -f "${REPLAY_DIRECTORY}/status" ]];
     then
      echo "Previous replay exit code"
      status=$(cat "${REPLAY_DIRECTORY}/status")
      echo "$status"
      if [ "$status" -eq 0 ];
      then
        echo "Previous replay datadir is valid, exiting"
        exit 0
      fi
     fi
     echo "Didn't find a valid replay, performing a fresh one..."
     ls "${REPLAY_DIRECTORY}" -lath
     rm "${REPLAY_DIRECTORY}/*" -rf
     touch "${REPLAY_DIRECTORY}/replay_running"
     echo -e "\e[0Ksection_end:$(date +%s):check\r\e[0K"

     echo -e "\e[0Ksection_start:$(date +%s):prepare[collapsed=true]\r\e[0KPreparing replay directory..."
     echo "Hardlinking the block_log..."
     mkdir -p "${REPLAY_DIRECTORY}/blockchain"
     cp -u "${BLOCK_LOG_SOURCE_DIR}/block_log" "${REPLAY_DIRECTORY}/..${BLOCK_LOG_SOURCE_DIR}/block_log"
     ln "${REPLAY_DIRECTORY}/..${BLOCK_LOG_SOURCE_DIR}/block_log" "${REPLAY_DIRECTORY}/blockchain/block_log"
     if [ -e $BLOCK_LOG_SOURCE_DIR/block_log.artifacts ];
     then
      echo "Copying the artifacts file..." 
      cp "${BLOCK_LOG_SOURCE_DIR}/block_log.artifacts" "${REPLAY_DIRECTORY}/blockchain/block_log.artifacts"
     fi
     chown -R 1000:100 "${REPLAY_DIRECTORY}/blockchain"
     echo -e "\e[0Ksection_end:$(date +%s):prepare\r\e[0K"
     
     echo -e "\e[0Ksection_start:$(date +%s):replay[collapsed=true]\r\e[0KReplaying HAF API node..."
     docker-entrypoint.sh docker version
     cd /haf-api-node
     docker-entrypoint.sh docker compose up --detach --quiet-pull
     cd "${CI_PROJECT_DIR}"
     until [[ $(docker-entrypoint.sh docker exec --env LC_ALL="C" haf-world-hivemind-block-processing-1 psql "${HAF_DB_URL}" --quiet --tuples-only --no-align --command "${PSQL_COMMAND}") == "${LAST_BLOCK_NUMBER}" ]]
     do
      CURRENT_BLOCK=$(docker-entrypoint.sh docker exec --env LC_ALL="C" haf-world-hivemind-block-processing-1 psql "${HAF_DB_URL}" --quiet --tuples-only --no-align --command "${PSQL_COMMAND}")
      echo -e "Waiting for Hivemind replay to finish...\n Current block: ${CURRENT_BLOCK}"
      sleep 10
     done
     cd /haf-api-node
     docker-entrypoint.sh docker compose stop
     cd "${CI_PROJECT_DIR}"
     status=$(docker-entrypoint.sh docker inspect haf-world-haf-1 --format="{{.State.ExitCode}}")
     echo "$status" > "${REPLAY_DIRECTORY}/status"
     echo -e "\e[0Ksection_end:$(date +%s):replay\r\e[0K"
  after_script:
    - |
      cd /haf-api-node
      docker-entrypoint.sh docker compose logs --no-color > "${CI_PROJECT_DIR}/haf_api_node.log"
      docker-entrypoint.sh docker compose down --volumes
      cd "${CI_PROJECT_DIR}"
      rm -f "${REPLAY_DIRECTORY}/replay_running"
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - haf_api_node.log
  tags:
    - data-cache-storage

######## End replay ########

######## Test ########

# Creates a copy of replay data to b used in the tests
haf_api_node_replay_data_copy:
  extends: .job-defaults
  stage: test
  needs:
    - haf-node-replay
  image: 
    name: registry.gitlab.syncad.com/hive/haf_api_node/compose:${CI_COMMIT_SHORT_SHA}
    entrypoint: [ "" ]
  script:
    - |
      echo "Copying replay data to ${REPLAY_PIPELINE_DIRECTORY}"
      cp --recursive "${REPLAY_DIRECTORY}" "${REPLAY_PIPELINE_DIRECTORY}"
  tags:
    - data-cache-storage

# Tests if HAF API node is working properly
haf_api_node_test:
  extends: .job-defaults
  stage: test
  needs:
    - haf_api_node_replay_data_copy
  image: 
    name: registry.gitlab.syncad.com/hive/haf_api_node/compose:${CI_COMMIT_SHORT_SHA}
    entrypoint: [ "" ]
  variables:
    TOP_LEVEL_DATASET_MOUNTPOINT: "${REPLAY_PIPELINE_DIRECTORY}"
    ARGUMENTS: "--plugin database_api --replay-blockchain --stop-at-block 5000000"
    PUBLIC_HOSTNAME: "docker"
    DOCKER_DRIVER: "overlay2"
    CI_DEBUG_SERVICES: "true" # Change to true to debug services in this job
    GIT_STRATEGY: "none"
  services:
    - name: registry.gitlab.syncad.com/hive/haf_api_node/dind:${CI_COMMIT_SHORT_SHA}
      alias: docker
    - name: registry.gitlab.syncad.com/hive/haf_api_node/compose:${CI_COMMIT_SHORT_SHA}
  script:
    - |
      set -e
      
      sleep 60
      docker-entrypoint.sh docker ps --all

      echo "Waiting for HAproxy to start..."
      until [[ $(docker-entrypoint.sh docker inspect --format "{{.State.Health.Status}}" haf-world-haproxy-1) == "healthy" ]]
      do
        echo "Waiting for HAproxy to start..."
        sleep 10
      done

      echo -e "Testing endpoints...\nHive..."
      curl -vk -X POST --data '{"jsonrpc":"2.0", "method":"condenser_api.get_block", "params":[1], "id":1}' https://nb-kbotor-3:8443/ # Hive
      echo "HAfAH..."
      curl -vk -X POST https://nb-kbotor-3:8443/hafah/get_version # HAfAH
      echo "Hivemind..."
      curl -vk -X POST --data '{"jsonrpc":"2.0", "method":"condenser_api.get_trending_tags", "id":1}' https://nb-kbotor-3:8443/ # Hivemind
  after_script:
    - |
      cd /haf-api-node
      docker-entrypoint.sh docker compose logs --no-color > "${CI_PROJECT_DIR}/haf_api_node.log"
      docker-entrypoint.sh docker compose down --volumes
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - haf_api_node.log
  tags:
    - data-cache-storage

######## End test ########

######## Cleanup ########

# Deletes replay data used by the tests and created by haf_api_node_replay_data_copy
cleanup_haf_api_node_pipeline_cache:
  extends: 
    - .cleanup_cache_manual_template
  stage: cleanup
  variables:
    CLEANUP_PATH_PATTERN: "${REPLAY_PIPELINE_DIRECTORY}*"
  when: always
  tags:
    - data-cache-storage

# Deletes all HAF API node replay data
cleanup_haf_api_node_cache_manual:
  extends: 
    - .cleanup_cache_manual_template
  stage: cleanup
  variables:
    CLEANUP_PATH_PATTERN: "${REPLAY_DIRECTORY_PREFIX}*"
  tags:
    - data-cache-storage

# Deletes HAF API node replay data older than 7 days
cleanup_old_haf_api_node_cache:
  extends:
    - .cleanup_old_cache_template
  stage: cleanup
  variables:
    CLEANUP_PATH_PATTERN: "${REPLAY_DIRECTORY_PREFIX}*"
  tags:
    - data-cache-storage

######## End cleanup ########