services:
  pghero:
    image: ankane/pghero:v3.3.3
    profiles:
      - admin
    environment:
      DATABASE_URL: postgres://pghero@haf:5432/haf_block_log
      RAILS_RELATIVE_URL_ROOT: /admin/pghero
    networks:
      - haf-network
    init: true
    depends_on:
      haf:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:7.7
    profiles:
      - admin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@haf.world"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    networks:
      - haf-network
    init: true
    volumes:
      - type: volume
        source: pgadmin_data
        target: /var/lib/pgadmin
    configs:
      - source: pgadmin_servers
        target: /pgadmin4/servers.json
        uid: "5050"
        gid: "5050"
      - source: pgadmin_passwords
        target: /pgadmin4/pgpass
        uid: "5050"
        gid: "5050"


configs:
  # this config pre-loads the haf database server into pgadmin so you don't have to add it by hand
  pgadmin_servers:
    file: ./pgadmin/servers.json
  pgadmin_passwords:
    file: ./pgadmin/pgpass

volumes:
  # this volume stores your pgadmin state
  pgadmin_data:
