services:
  balance-tracker-install:
    image: ${BALANCE_TRACKER_REGISTRY:-registry.gitlab.syncad.com/hive/balance_tracker}:${BALANCE_TRACKER_VERSION:-haf_api_node}
    profiles:
      - apps
      - hafbe
      - balance-tracker-setup
    environment:
      POSTGRES_HOST: haf
    networks:
      haf-network:
    command:
      - install_app
    depends_on:
      haf:
        condition: service_healthy
  balance-tracker-uninstall:
    image: ${BALANCE_TRACKER_REGISTRY:-registry.gitlab.syncad.com/hive/balance_tracker}:${BALANCE_TRACKER_VERSION:-haf_api_node}
    profiles:
      - balance-tracker-uninstall
    environment:
      POSTGRES_HOST: haf
    networks:
      haf-network:
    command:
      - uninstall_app
    depends_on:
      balance-tracker-install:
        condition: service_completed_successfully
  balance-tracker-block-processing:
    image: ${BALANCE_TRACKER_REGISTRY:-registry.gitlab.syncad.com/hive/balance_tracker}:${BALANCE_TRACKER_VERSION:-haf_api_node}
    profiles:
      - balance-tracker-standalone
    environment:
      POSTGRES_HOST: haf
    networks:
      haf-network:
    command:
      - process_blocks
    healthcheck:
      test: ["CMD-SHELL","/app/block-processing-healthcheck.sh"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 48h
    depends_on:
      balance-tracker-install:
        condition: service_completed_successfully
  balance-tracker-postgrest:
    image: ${POSTGREST_REGISTRY:-postgrest/postgrest}:${POSTGREST_VERSION:-latest}
    profiles:
      - apps
    environment:
      PGRST_ADMIN_SERVER_PORT: 3001
      PGRST_DB_URI: postgresql://haf_app_admin@haf/haf_block_log
      PGRST_DB_SCHEMA: btracker_app
      PGRST_DB_ANON_ROLE: btracker_user
      PGRST_DB_POOL: 20
      PGRST_DB_POOL_ACQUISITION_TIMEOUT: 10
      PGRST_OPENAPI_SERVER_PROXY_URI: http://${PUBLIC_HOSTNAME}/btracker_api/
    networks:
      haf-network:
    depends_on:
      haf:
        condition: service_healthy
  balance-tracker-swagger:
    image: ${SWAGGER_REGISTRY:-swaggerapi/swagger-ui}:${SWAGGER_VERSION:-latest}
    profiles:
      - apps
    environment:
      API_URL: http://${PUBLIC_HOSTNAME}/btracker_api/
    networks:
      haf-network:
    #healthcheck:
    #  test: ["CMD-SHELL","curl -f localhost:8080"]
    depends_on:
      balance-tracker-postgrest:
        condition: service_started
          #balance-tracker-agent-check:
          #  image: alpine:3.18.3
          #  entrypoint:
