services:
  balance-tracker-install:
    image: ${BALANCE_TRACKER_REGISTRY:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/balance_tracker}:${BALANCE_TRACKER_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - apps
      - hafbe
      - balance-tracker-setup
    environment:
      POSTGRES_HOST: haf
    networks:
      haf-network:
    command:
      - install_app
      - --schema=${BTRACKER_SCHEMA:-hafbe_bal}
    depends_on:
      haf:
        condition: service_healthy
  balance-tracker-uninstall:
    image: ${BALANCE_TRACKER_REGISTRY:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/balance_tracker}:${BALANCE_TRACKER_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - balance-tracker-uninstall
    environment:
      POSTGRES_HOST: haf
    networks:
      haf-network:
    command:
      - uninstall_app
      - --schema=${BTRACKER_SCHEMA:-hafbe_bal}
    depends_on:
      haf:
        condition: service_healthy
  balance-tracker-block-processing:
    image: ${BALANCE_TRACKER_REGISTRY:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/balance_tracker}:${BALANCE_TRACKER_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - balance-tracker-standalone
    environment:
      POSTGRES_HOST: haf
    networks:
      haf-network:
    command:
      - process_blocks
      - --schema=${BTRACKER_SCHEMA:-hafbe_bal}
    healthcheck:
      test: ["CMD-SHELL","/app/block-processing-healthcheck.sh"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 48h
    depends_on:
      balance-tracker-install:
        condition: service_completed_successfully
      haf:
        condition: service_healthy
  balance-tracker-postgrest:
    image: ${POSTGREST_REGISTRY:-registry.gitlab.syncad.com/hive/haf_api_node/postgrest}:${POSTGREST_VERSION:-latest}
    profiles:
      - apps
      - balance-tracker-standalone
      - hafbe
    environment:
      PGRST_ADMIN_SERVER_PORT: 3001
      PGRST_DB_URI: postgresql://btracker_user@haf/haf_block_log
      PGRST_DB_SCHEMA: btracker_endpoints
      PGRST_DB_ANON_ROLE: btracker_user
      PGRST_DB_POOL: 20
      PGRST_DB_POOL_ACQUISITION_TIMEOUT: 10
      PGRST_DB_EXTRA_SEARCH_PATH: ${BTRACKER_SCHEMA:-hafbe_bal}
      # PGRST_OPENAPI_SERVER_PROXY_URI: http://${PUBLIC_HOSTNAME}/btracker_api/
    healthcheck:
      test: ["CMD-SHELL", "wget --timeout=2 -nv -t1 --spider 127.0.0.1:3001/ready || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 1m
    networks:
      haf-network:
    depends_on:
      balance-tracker-install:
        condition: service_completed_successfully
      haf:
        condition: service_healthy
  balance-tracker-swagger:
    image: ${SWAGGER_REGISTRY:-swaggerapi/swagger-ui}:${SWAGGER_VERSION:-latest}
    profiles:
      # right now, hafbe_btracker doesn't have the correct annotations to generate a
      # usable swagger UI, so we haven't plumbed swagger into the stack, and you
      # probably shouldn't bother running it.
      # Once they work, we should put these services into the same groups as their
      # postgrest siblings, but for now we put them into a "swagger" group to
      # effectively disable them
      - swagger
    environment:
      API_URL: http://${PUBLIC_HOSTNAME}/btracker_api/
    networks:
      haf-network:
    #healthcheck:
    #  test: ["CMD-SHELL","curl -f 127.0.0.1:8080"]
    depends_on:
      balance-tracker-postgrest:
        condition: service_started
