# Note, most of the services in this file are only used in the uncommon case where
# the node is running Balance Tracker standalone.  Balance Tracker is typically
# run as part of HAF Block Explorer, and the services related to that usage are
# in haf_block_explorer.yaml.
# The exception is the postgrest server & rewriter.  Those are shared between the two
services:
  balance-tracker-install:
    image: ${BALANCE_TRACKER_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/balance_tracker}:${BALANCE_TRACKER_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - balance-tracker-standalone
    environment:
      POSTGRES_HOST: haf
    networks:
      haf-network:
    command:
      - install_app
      - --schema=btracker_app
      - --swagger-url=${PUBLIC_HOSTNAME}
    depends_on:
      haf:
        condition: service_healthy
  # to uninstall Balance Tracker (standalone), shut down the stack and run a command like:
  #   docker compose --profile core --profile balance-tracker-standalone-uninstall up -d
  balance-tracker-uninstall:
    image: ${BALANCE_TRACKER_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/balance_tracker}:${BALANCE_TRACKER_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - balance-tracker-standalone-uninstall
    environment:
      POSTGRES_HOST: haf
    networks:
      haf-network:
    command:
      - uninstall_app
      - --schema=btracker_app
    depends_on:
      haf:
        condition: service_healthy
  balance-tracker-block-processing:
    image: ${BALANCE_TRACKER_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/balance_tracker}:${BALANCE_TRACKER_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - balance-tracker-standalone
    environment:
      POSTGRES_HOST: haf
      POSTGRES_USER: btracker_owner
    networks:
      haf-network:
    command:
      - process_blocks
      - --schema=btracker_app
    healthcheck:
      test: ["CMD-SHELL","/app/block-processing-healthcheck.sh"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 48h
    depends_on:
      balance-tracker-install:
        condition: service_completed_successfully
      haf:
        condition: service_healthy
  balance-tracker-postgrest:
    image: ${POSTGREST_IMAGE:-registry.gitlab.syncad.com/hive/haf_api_node/postgrest}:${POSTGREST_VERSION:-latest}
    profiles:
      - apps
      - balance-tracker-standalone
      - hafbe
    environment:
      PGRST_ADMIN_SERVER_PORT: 3001
      PGRST_DB_URI: postgresql://btracker_user@haf/haf_block_log?application_name=balance_tracker_postgrest
      PGRST_DB_SCHEMA: btracker_endpoints
      PGRST_DB_ANON_ROLE: btracker_user
      PGRST_DB_POOL: 20
      PGRST_DB_ROOT_SPEC: root
      PGRST_DB_POOL_ACQUISITION_TIMEOUT: 10
      PGRST_DB_EXTRA_SEARCH_PATH: ${BTRACKER_SCHEMA:-hafbe_bal}
      # PGRST_OPENAPI_SERVER_PROXY_URI: http://${PUBLIC_HOSTNAME}/btracker_api/
      PGRST_LOG_LEVEL: ${BALANCE_TRACKER_SERVER_LOG_LEVEL:-error}
    healthcheck:
      test: ["CMD-SHELL", "wget --timeout=2 -nv -t1 --spider 127.0.0.1:3001/ready || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 1m
    networks:
      haf-network:
    depends_on:
      balance-tracker-install:
        condition: service_completed_successfully
        required: false # allow this service to be missing (when only running hafbe)
      block-explorer-install-balance-tracker:
        condition: service_completed_successfully
        required: false # allow this service to be missing (when only running standalone)
      haf:
        condition: service_healthy
  balance-tracker-postgrest-rewriter:
    image: ${BALANCE_TRACKER_REWRITER_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/balance_tracker/postgrest-rewriter}:${BALANCE_TRACKER_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - apps
      - balance-tracker-standalone
      - hafbe
    healthcheck:
      test: ["CMD-SHELL", "wget --timeout=2 -nv -t1 --spider 127.0.0.1:81/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 1m
    depends_on:
      balance-tracker-postgrest:
        condition: service_healthy
    networks:
      - haf-network
