name: ${PROJECT_NAME}

include:
  - haf_base.yaml
  - backend.yaml
  - hafah.yaml
  - hivemind.yaml
  - balance_tracker.yaml
  - reputation_tracker.yaml
  - nft_tracker.yaml
  - haf_block_explorer.yaml
  - varnish.yaml
  - ${JSONRPC_API_SERVER_NAME:-drone}.yaml
  - pgbouncer.yaml
  - haproxy.yaml
  - caddy.yaml
  - monitoring.yaml
  - swagger.yaml
  - hivesense.yaml
  - hivesense-${HIVESENSE_CONFIGURATION:-sync}.yaml
  - proxy_whitelist.yaml
  - hafsql.yaml
  - ui.yaml
  - status.yaml
  - hive.yaml

networks:
  haf-network:
    name: ${NETWORK_NAME}
    enable_ipv6: true
