version: "3.8"
name: ${PROJECT_NAME}

include:
  - haf_base.yaml
  - backend.yaml
  - hafah.yaml
  - hivemind.yaml
  - balance_tracker.yaml
  - haf_block_explorer.yaml
  - jussi.yaml
  - varnish.yaml
  - haproxy.yaml
  - caddy.yaml

networks:
  haf-network:
    name: ${NETWORK_NAME}
