name: ${PROJECT_NAME}

include:
  - haf_base.yaml
  - backend.yaml
  - hafah.yaml
  - hivemind.yaml
  - balance_tracker.yaml
  - haf_block_explorer.yaml
  - varnish.yaml
  - ${JSONRPC_API_SERVER_NAME:-jussi}.yaml
  - haproxy.yaml
  - caddy.yaml
  - monitoring.yaml
  - swagger.yaml

networks:
  haf-network:
    name: ${NETWORK_NAME}
