services:
  drone:
    image: ${DRONE_REGISTRY:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/haf_api_node/drone}:${DRONE_VERSION:-latest}
    profiles:
      - servers
    environment:
      RUST_LOG: drone=trace
    volumes:
      - type: bind
        source: ./drone/config.json
        target: /config.json
        read_only: true
    depends_on:
      haproxy:
        condition: service_healthy
    networks:
      - haf-network
  # to use our log analysis tools, we need to capture drone's traffic using a 
  # specific nginx logging config.  To do this, rename the actual drone
  # service above to 'jussi-real', then uncomment the next section. 
  # drone:
  #   image: nginx
  #   profiles:
  #     - servers
  #   volumes:
  #     - type: bind
  #       source: ./drone/nginx.conf
  #       target: /etc/nginx/nginx.conf
  #       read_only: true
  #     - type: bind
  #       source: ${HAF_LOG_DIRECTORY}/drone
  #       target: /var/log/drone
  #   depends_on:
  #     drone-real:
  #       condition: service_started
  #   ports:
  #     - "${HAF_API_NODE_EXPOSED_IPADDR:-0.0.0.0}:9001:9000"
  #   networks:
  #     - haf-network
