services:
  drone:
    image: ${DRONE_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/drone}:${DRONE_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - servers
      - drone
    environment:
      RUST_LOG: ${DRONE_LOG_LEVEL:-warn,access_log=info}
    volumes:
      - type: bind
        source: ./drone/config.yaml
        target: /config.yaml
        read_only: true
      - type: bind
        source: ${HAF_LOG_DIRECTORY:-${TOP_LEVEL_DATASET_MOUNTPOINT}/logs}/drone
        target: /var/log/drone
    depends_on:
      haproxy:
        condition: service_healthy
    networks:
      - haf-network
