services:
  haf-block-explorer-setup:
    image: ${HAF_BLOCK_EXPLORER_SETUP_REGISTRY:-registry.gitlab.syncad.com/hive/haf_block_explorer}:${HAF_BLOCK_EXPLORER_SETUP_VERSION:-latest}
    profiles:
      - apps
    environment:
      POSTGRES_HOST: haf
    command:
      - setup_db
    networks:
      haf-network:
    depends_on:
      haf:
        condition: service_healthy
      balance-tracker-setup:
        condition: service_completed_successfully
      hafah-setup:
        condition: service_completed_successfully
  haf-block-explorer-block-processing:
    image: ${HAF_BLOCK_EXPLORER_SETUP_REGISTRY:-registry.gitlab.syncad.com/hive/haf_block_explorer}:${HAF_BLOCK_EXPLORER_SETUP_VERSION:-latest}
    profiles:
      - apps-disabled-for-now
    environment:
      POSTGRES_HOST: haf
    command:
      - process_blocks
    networks:
      haf-network:
    depends_on:
      haf-block-explorer-setup:
        condition: service_completed_successfully
      balance-tracker-setup:
        condition: service_completed_successfully
      hafah-setup:
        condition: service_completed_successfully
  haf-block-explorer-postgrest:
    image: ${POSTGREST_REGISTRY:-postgrest/postgrest}:${POSTGREST_VERSION:-latest}
    profiles:
      - apps-disabled-for-now
    environment:
      PGRST_ADMIN_SERVER_PORT: 3001
      PGRST_DB_URI: postgresql://hafbe_owner@haf/haf_block_log
      PGRST_DB_SCHEMA: hafbe_endpoints
      PGRST_DB_ANON_ROLE: hafbe_user
      PGRST_DB_POOL: 20
      PGRST_DB_POOL_ACQUISITION_TIMEOUT: 10
      PGRST_OPENAPI_SERVER_PROXY_URI: http://${PUBLIC_HOSTNAME}/hafbe_api/
    networks:
      haf-network:
    depends_on:
      haf-block-explorer-setup:
        condition: service_completed_successfully
