services:
  block-explorer-install:
    image: ${HAF_BLOCK_EXPLORER_REGISTRY:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/haf_block_explorer}:${HAF_BLOCK_EXPLORER_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - apps
      - hafbe
    environment:
      POSTGRES_HOST: haf
    command:
      - install_app
    networks:
      haf-network:
    depends_on:
      haf:
        condition: service_healthy
      balance-tracker-install:
        condition: service_completed_successfully
      hafah-install:
        condition: service_completed_successfully
  block-explorer-uninstall:
    image: ${HAF_BLOCK_EXPLORER_REGISTRY:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/haf_block_explorer}:${HAF_BLOCK_EXPLORER_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - block-explorer-uninstall
    environment:
      POSTGRES_HOST: haf
    command:
      - uninstall_app
      - --skip-btracker
    networks:
      haf-network:
    depends_on:
      haf:
        condition: service_healthy
  block-explorer-uninstall-balance-tracker:
    image: ${BALANCE_TRACKER_REGISTRY:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/balance_tracker}:${BALANCE_TRACKER_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - block-explorer-uninstall
    environment:
      POSTGRES_HOST: haf
    networks:
      haf-network:
    command:
      - uninstall_app
    depends_on:
      block-explorer-uninstall:
        condition: service_completed_successfully
      haf:
        condition: service_healthy
  block-explorer-block-processing:
    image: ${HAF_BLOCK_EXPLORER_REGISTRY:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/haf_block_explorer}:${HAF_BLOCK_EXPLORER_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - apps
      - hafbe
    environment:
      POSTGRES_HOST: haf
    command:
      - process_blocks
    networks:
      haf-network:
    depends_on:
      block-explorer-install:
        condition: service_completed_successfully
      haf:
        condition: service_healthy
  block-explorer-postgrest:
    image: ${POSTGREST_REGISTRY:-registry.gitlab.syncad.com/hive/haf_api_node/postgrest}:${POSTGREST_VERSION:-latest}
    profiles:
      - apps
      - hafbe
    environment:
      PGRST_ADMIN_SERVER_PORT: 3001
      PGRST_DB_URI: postgresql://hafbe_user@haf/haf_block_log
      PGRST_DB_SCHEMA: hafbe_endpoints
      PGRST_DB_ANON_ROLE: hafbe_user
      PGRST_DB_POOL: 20
      PGRST_DB_POOL_ACQUISITION_TIMEOUT: 10
      # PGRST_OPENAPI_SERVER_PROXY_URI: http://${PUBLIC_HOSTNAME}/hafbe_api/
    networks:
      haf-network:
    healthcheck:
      test: ["CMD-SHELL", "wget --timeout=2 -nv -t1 --spider http://127.0.0.1:3000/rpc/get_hafbe_version || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 1m
    depends_on:
      block-explorer-install:
        condition: service_completed_successfully
      haf:
        condition: service_healthy
