services:
  hafah-install:
    image: ${HAFAH_REGISTRY:-registry.gitlab.syncad.com/hive/hafah/instance}:${HAFAH_VERSION:-haf_api_node}
    profiles:
      - apps
      - hafah
      - hafbe
      - haf-block-explorer-drop-db
    environment:
      POSTGRES_URL: postgresql://haf_app_admin@haf/haf_block_log
    networks:
      haf-network:
    depends_on:
      haf:
        condition: service_healthy
  hafah-uninstall:
    image: ${HAFAH_REGISTRY:-registry.gitlab.syncad.com/hive/hafah/instance}:${HAFAH_VERSION:-haf_api_node}
    profiles:
      - hafah-uninstall
    environment:
      POSTGRES_URL: postgresql://haf_app_admin@haf/haf_block_log
    networks:
      haf-network:
    depends_on:
      haf:
        condition: service_healthy
  hafah-postgrest:
    image: ${POSTGREST_REGISTRY:-postgrest/postgrest}:${POSTGREST_VERSION:-latest}
    profiles:
      - apps
      - hafah
    environment:
      PGRST_ADMIN_SERVER_PORT: 3001
      PGRST_DB_URI: postgresql://hafah_user@haf/haf_block_log
      PGRST_DB_SCHEMA: hafah_endpoints, hafah_api_v1, hafah_api_v2
      PGRST_DB_ROOT_SPEC: home
      PGRST_DB_ANON_ROLE: hafah_user
      PGRST_DB_POOL: 20
      PGRST_DB_POOL_ACQUISITION_TIMEOUT: 10
      PGRST_OPENAPI_SERVER_PROXY_URI: http://localhost:3000
    networks:
      haf-network:
    depends_on:
      hafah-install:
        condition: service_completed_successfully
  hafah-benchmarks-old-style:
    image: registry.gitlab.syncad.com/hive/tests_api/benchmark_aio:latest
    profiles:
      - hafah-benchmarks
    environment:
      SKIP_VERSION1: 1
      ADDITIONAL_ARGS1: --skip-version-check
      JMETER_WORKDIR: /workspace/wdir
      ADDRESS: hafah-postgrest
      PORT: 3000
      CALL_STYLE: old-style
      WDIR: /workspace
    volumes: 
      - type: bind
        source: ${HAF_DATA_DIRECTORY}/tests/hafah_api_benchmarks/old-style
        target: /workspace
    networks:
      haf-network:
    # note: when I enable this dependency which logically seems ok, 
    # docker restarts postgrest every time I bring up the benchmarks.
    # Other services don't do this, need to figure out why.  Suspect it's
    # because postgrest services don't have a health check.
    #depends_on:
    #  hafah-postgrest:
    #    condition: service_started
  hafah-benchmarks-new-style:
    image: registry.gitlab.syncad.com/hive/tests_api/benchmark_aio:latest
    profiles:
      - hafah-benchmarks
    environment:
      SKIP_VERSION1: 1
      ADDITIONAL_ARGS1: --skip-version-check
      JMETER_WORKDIR: /workspace/wdir
      ADDRESS: hafah-postgrest
      PORT: 3000
      CALL_STYLE: new-style
      WDIR: /workspace
    volumes: 
      - type: bind
        source: ${HAF_DATA_DIRECTORY}/tests/hafah_api_benchmarks/new-style
        target: /workspace
    networks:
      haf-network:
    # note: when I enable this dependency which logically seems ok, 
    # docker restarts postgrest every time I bring up the benchmarks.
    # Other services don't do this, need to figure out why.  Suspect it's
    # because postgrest services don't have a health check.
    #depends_on:
    #  hafah-postgrest:
    #    condition: service_started
