services:
  hafah-install:
    image: ${HAFAH_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/hafah}:${HAFAH_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - apps
      - hafah
      - hafbe
      - haf-block-explorer-drop-db
    environment:
      POSTGRES_URL: postgresql://haf_admin@haf/haf_block_log
    command:
      - install_app
      - --swagger-url=${PUBLIC_HOSTNAME}
    networks:
      haf-network:
    depends_on:
      haf:
        condition: service_healthy
  hafah-uninstall:
    image: ${HAFAH_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/hafah}:${HAFAH_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - hafah-uninstall
    environment:
      POSTGRES_URL: postgresql://haf_admin@haf/haf_block_log
    command:
      - uninstall_app
    networks:
      haf-network:
    depends_on:
      haf:
        condition: service_healthy
  hafah-postgrest:
    image: ${POSTGREST_IMAGE:-registry.gitlab.syncad.com/hive/haf_api_node/postgrest}:${POSTGREST_VERSION:-latest}
    profiles:
      - apps
      - hafah
      - hafbe
    environment:
      PGRST_ADMIN_SERVER_PORT: 3001
      PGRST_DB_URI: postgresql://hafah_user@haf/haf_block_log?application_name=hafah_postgrest
      PGRST_DB_SCHEMA: hafah_endpoints, hafah_api_v1, hafah_api_v2
      PGRST_DB_ROOT_SPEC: home
      PGRST_DB_ANON_ROLE: hafah_user
      PGRST_DB_POOL: 20
      PGRST_DB_POOL_ACQUISITION_TIMEOUT: 10
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    networks:
      haf-network:
    healthcheck:
      test: ["CMD-SHELL", "wget --timeout=2 -nv -t1 --spider 127.0.0.1:3001/ready || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 1m
    depends_on:
      hafah-install:
        condition: service_completed_successfully
      haf:
        condition: service_healthy
  hafah-postgrest-rewriter:
    image: ${HAFAH_REWRITER_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/hafah/postgrest-rewriter}:${HAFAH_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - apps
      - hafah
      - hafbe
    healthcheck:
      test: ["CMD-SHELL", "wget --timeout=2 -nv -t1 --spider 127.0.0.1:81/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 1m
    depends_on:
      hafah-postgrest:
        condition: service_healthy
    networks:
      - haf-network
  hafah-benchmarks-old-style:  #NOTE: need to first run mkdir -p ${HAF_DATA_DIRECTORY:-${TOP_LEVEL_DATASET_MOUNTPOINT}}/tests/hafah_api_benchmarks/old-style
    image: registry.gitlab.syncad.com/hive/tests_api/benchmark_aio:latest
    profiles:
      - hafah-benchmarks
    environment:
      SKIP_VERSION1: 1
      ADDITIONAL_ARGS1: --skip-version-check
      JMETER_WORKDIR: /workspace/wdir
      ADDRESS: hafah-postgrest
      PORT: 3000
      CALL_STYLE: old-style
      WDIR: /workspace
    volumes: 
      - type: bind
        source: ${HAF_DATA_DIRECTORY:-${TOP_LEVEL_DATASET_MOUNTPOINT}}/tests/hafah_api_benchmarks/old-style
        target: /workspace
    networks:
      haf-network:
    depends_on:
      hafah-postgrest:
        condition: service_healthy
  # Note: new style benchmarks don't work.  Not sure if this is just a problem with the 
  # environment set up below, or if it's a general problem and there's no way of running
  # them that will work.
  #
  # hafah-benchmarks-new-style:
  #   image: registry.gitlab.syncad.com/hive/tests_api/benchmark_aio:latest
  #   profiles:
  #     - hafah-benchmarks
  #   environment:
  #     SKIP_VERSION1: 1
  #     ADDITIONAL_ARGS1: --skip-version-check
  #     JMETER_WORKDIR: /workspace/wdir
  #     ADDRESS: hafah-postgrest
  #     PORT: 3000
  #     CALL_STYLE: new-style
  #     WDIR: /workspace
  #   volumes: 
  #     - type: bind
  #       source: ${HAF_DATA_DIRECTORY:-${TOP_LEVEL_DATASET_MOUNTPOINT}}/tests/hafah_api_benchmarks/new-style
  #       target: /workspace
  #   networks:
  #     haf-network:
  #   depends_on:
  #     hafah-postgrest:
  #       condition: service_healthy
