services:
  hafsql:
    profiles:
      - hafsql
    image: mahdiyari/hafsql:${HAFSQL_VERSION}
    networks:
      - haf-network
    tty: true
    stdin_open: true
    environment:
      HAFSQL_PGHOST: haf
      # Can disable parts of hafsql if not needed
      HAFSQL_BALANCES: true
      HAFSQL_ACCOUNTS: true
      HAFSQL_FOLLOWS: true # follows, mutes, blacklists
      HAFSQL_COMMUNITIES: true
      HAFSQL_RC_DELEGATIONS: true
      HAFSQL_DELEGATIONS: true
      HAFSQL_PROPOSALS: true
      HAFSQL_COMMENTS: true
      HAFSQL_REBLOGS: true # depends on HAFSQL_COMMENTS
      HAFSQL_REWARDS: true # depends on HAFSQL_COMMENTS
      HAFSQL_REPUTATIONS: true # depends on HAFSQL_COMMENTS
      HAFSQL_MARKET: true
      HAFSQL_PUBLICUSER: true
      HAFSQL_PUBLICUSERNAME: ${HAFSQL_PUBLIC_USERNAME:-hafsql_public}
      HAFSQL_PUBLICPASSWORD: ${HAFSQL_PUBLIC_PASSWORD:-hafsql_public}
      API_PREFIX: /hafsql
    depends_on:
      haf:
        condition: service_healthy
      hivemind-install:
        condition: service_completed_successfully
      block-explorer-install-balance-tracker:
        condition: service_completed_successfully
        required: false
      balance-tracker-install:
        condition: service_completed_successfully
        required: false
      reputation-tracker-install:
        condition: service_completed_successfully
    labels:
      # for Swagger UI
      - "io.hive.swagger.url=/hafsql/openapi.json"
      - "io.hive.swagger.name=HafSQL"
      - "io.hive.swagger.order=7"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5

  hafsql-uninstall:
    profiles:
      - hafsql-uninstall
    image: mahdiyari/hafsql:${HAFSQL_VERSION}
    networks:
      - haf-network
    tty: true
    stdin_open: true
    stop_grace_period: 10m
    command: purge
    environment:
      HAFSQL_PGHOST: haf
    depends_on:
      haf:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5
