services:
  haproxy:
    image: haproxy:2.8.2-alpine
    profiles:
      - servers
    volumes:
      - type: bind
        source: ./haproxy/haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
        read_only: true
    networks:
      - haf-network
  haproxy-healthchecks:
    image: healthchecks
    environment:
      POSTGRES_URL: postgresql://haf_app_admin@haf/haf_block_log
    profiles:
      - servers
    networks:
      - haf-network
