services:
  haproxy:
    image: haproxy:2.9.3-alpine
    profiles:
      - servers
    environment:
      SYNC_BROADCAST_BACKEND_SERVER: "${SYNC_BROADCAST_BACKEND_SERVER:-api.hive.blog}"
      SYNC_BROADCAST_BACKEND_PORT: "${SYNC_BROADCAST_BACKEND_PORT:-443}"
      SYNC_BROADCAST_BACKEND_SSL: "${SYNC_BROADCAST_BACKEND_SSL:-ssl}"
    volumes:
      - type: bind
        source: ./haproxy/haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
        read_only: true
    networks:
      - haf-network
    healthcheck:
      test: wget -q --spider 127.0.0.1:8001 
  haproxy-healthchecks:
    image: registry.gitlab.syncad.com/hive/haf_api_node/haproxy-healthchecks:${HAPROXY_HEALTHCHECKS_VERSION:-latest}
    environment:
      POSTGRES_URL: postgresql://haf_admin@haf/haf_block_log
      POSTGRES_URL_HAFBE: postgresql://hafbe_user@haf/haf_block_log
      POSTGRES_URL_BTRACKER: postgresql://btracker_user@haf/haf_block_log
    profiles:
      - servers
    networks:
      - haf-network
