services:
  haproxy:
    image: ${HAPROXY_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/haf_api_node/haproxy}:${HAPROXY_VERSION:-latest}
    profiles:
      - servers
    environment:
      SYNC_BROADCAST_BACKEND_SERVER: "${SYNC_BROADCAST_BACKEND_SERVER:-api.hive.blog}"
      SYNC_BROADCAST_BACKEND_PORT: "${SYNC_BROADCAST_BACKEND_PORT:-443}"
      SYNC_BROADCAST_BACKEND_SSL: "${SYNC_BROADCAST_BACKEND_SSL:-ssl}"
    volumes:
      - type: bind
        source: ./haproxy/haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
        read_only: true
      - type: bind
        source: ./haproxy/no-mailer.cfg
        target: /usr/local/etc/haproxy/_mailer.cfg
        read_only: true
    networks:
      - haf-network
    healthcheck:
      test: wget -q --spider 127.0.0.1:8001 
    command: -W -db -f /usr/local/etc/haproxy
  haproxy-healthchecks:
    image: ${HAPROXY_HEALTHCHECKS_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/haf_api_node/haproxy-healthchecks}:${HAPROXY_HEALTHCHECKS_VERSION:-${HIVE_API_NODE_VERSION}}
    environment:
      POSTGRES_URL: postgresql://haf_admin@haf/haf_block_log
      POSTGRES_URL_HAFBE: postgresql://hafbe_user@haf/haf_block_log
      POSTGRES_URL_BTRACKER: postgresql://btracker_user@haf/haf_block_log
      POSTGRES_URL_REPTRACKER: postgresql://reptracker_user@haf/haf_block_log
    healthcheck:
      test: ["CMD-SHELL", "/healthcheck_healthcheck.sh || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 1m
    profiles:
      - servers
      - haproxy-healthchecks
    networks:
      - haf-network
