version: '3.9'
name: "haf-world"

services:
  haproxy:
    image: haproxy:2.8.2-alpine
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./haproxy/haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
        read_only: true
    networks:
      - haf-network

networks:
  haf-network:
    name: ${NETWORK_NAME}
