services:
  haproxy:
    image: haproxy:2.8.2
    profiles:
      - servers
    volumes:
      - type: bind
        source: ./haproxy/haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
        read_only: true
    networks:
      - haf-network
    healthcheck:
      test: |
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/8001; echo -e "GET / HTTP/1.1\nConnection: close\n" >&3; cat <&3 | grep -q "200 OK"'
  haproxy-healthchecks:
    image: registry.gitlab.syncad.com/hive/haf_api_node/haproxy-healthchecks:${HAPROXY_HEALTHCHECKS_VERSION:-latest}
    environment:
      POSTGRES_URL: postgresql://haf_app_admin@haf/haf_block_log
      POSTGRES_URL_HAFBE: postgresql://hafbe_user@haf/haf_block_log
      POSTGRES_URL_BTRACKER: postgresql://btracker_user@haf/haf_block_log
    profiles:
      - servers
    networks:
      - haf-network
