services:
  # use this ollama instance for testing
  # for production it is better to use remote server with CUDA GPU cards
  hivesense-ollama:
    image: ollama/ollama:0.6.5
    profiles:
      - ollama
    environment:
      - TZ=America/New_York
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=16
      - OLLAMA_NUM_THREADS=16
      - OLLAMA_KEEP_ALIVE=-1
      - OLLAMA_MODELS=/tmp/ollama
    tty: true
    ports:
      - "11435:11434"
    networks:
      haf-network:
    volumes:
      - type: bind
        source: ${HAF_DATA_DIRECTORY}/ollama
        target: /tmp/ollama
  hivesense-install-schema:
    image: ${HIVESENSE_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/hivesense}:${HIVESENSE_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - hivesense
    environment:
      POSTGRES_HOST: haf
    command:
      - install_app
      - "--llm=${HIVESENSE_MODEL:-yxchia/multilingual-e5-base:F16}"
      - "--vector_size=${HIVESENSE_VECTOR_SIZE:-768}"
      - "--ollama=${HIVESENSE_OLLAMA:-http://hivesense-ollama:11434}"
      - "--start_block=${HIVESENSE_START_BLOCK:-1}"
      - "--parallel_workers=${HIVESENSE_WORKERS:-16}"
      - "--swagger-url=${PUBLIC_HOSTNAME}/"
    networks:
      haf-network:
    depends_on:
      haf:
        condition: service_healthy
      hivemind-install:
        condition: service_completed_successfully
  # to uninstall Hivesense, shut down the stack and run a command like:
  #   docker compose --profile core --profile block-explorer-uninstall up -d
  hivesense-uninstall:
    image: ${HIVESENSE_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/hivesense}:${HIVESENSE_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - hivesense-uninstall
    environment:
      POSTGRES_HOST: haf
    command:
      - uninstall_app
    networks:
      haf-network:
    depends_on:
      haf:
        condition: service_healthy
  hivesense-block-processing:
    image: ${HIVESENSE_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/haf_block_explorer}:${HIVESENSE_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - hivesense
    environment:
      POSTGRES_HOST: haf
      POSTGRES_USER: hivesense_owner
    command: >
      process_blocks ${HIVESENSE_SYNC_ARGS:-}
    networks:
      haf-network:
    healthcheck:
      test: ["CMD-SHELL","/app/block-processing-healthcheck.sh"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 48h
    depends_on:
      hivesense-install-schema:
        condition: service_completed_successfully
      haf:
        condition: service_healthy
  hivesense-postgrest-rewriter:
    image: ${HIVESENSE_REWRITER_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/hivesense/postgrest-rewriter}:${HIVESENSE_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - hivesense
    healthcheck:
      test: ["CMD-SHELL", "wget --timeout=2 -nv -t1 --spider 127.0.0.1:81/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 1m
    depends_on:
      hivesense-postgrest:
        condition: service_healthy
    networks:
      - haf-network
  hivesense-postgrest:
    image: ${POSTGREST_IMAGE:-registry.gitlab.syncad.com/hive/haf_api_node/postgrest}:${POSTGREST_VERSION:-latest}
    profiles:
      - hivesense
    environment:
      PGRST_ADMIN_SERVER_PORT: 3001
      PGRST_DB_URI: postgresql://hivesense_user@haf/haf_block_log?application_name=hivesense_postgrest
      PGRST_DB_SCHEMA: hivesense_endpoints
      PGRST_DB_ANON_ROLE: hivesense_user
      PGRST_DB_POOL: 20
      PGRST_DB_POOL_ACQUISITION_TIMEOUT: 10
      PGRST_DB_ROOT_SPEC: root
      PGRST_DB_EXTRA_SEARCH_PATH: hivesense_app
    networks:
      haf-network:
    healthcheck:
      test: ["CMD-SHELL", "wget --timeout=2 -nv -t1 --spider 127.0.0.1:3001/ready || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 1m
    depends_on:
      hivesense-install-schema:
        condition: service_completed_successfully
      haf:
        condition: service_healthy
  hivesense-swagger:
    image: swaggerapi/swagger-ui
    profiles:
      - hivesense
    environment:
      URLS: >-
        [{url: "https://${PUBLIC_HOSTNAME:-localhost}/hivesense-api/", name: "Hivesense"}]
    networks:
      haf-network:
    #healthcheck:
    #  test: ["CMD-SHELL","curl -f localhost:8080"]
    depends_on:
      hivesense-postgrest:
        condition: service_started
