services:
  hivemind-install:
    image: ${HIVEMIND_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/hivemind}:${HIVEMIND_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - apps
      - hivemind
    networks:
      haf-network:
    command:
      - "setup"
      - "--database-admin-url=postgresql://haf_admin@haf/haf_block_log"
    depends_on:
      haf:
        condition: service_healthy
      reputation-tracker-install:
        condition: service_completed_successfully

  hivemind-block-processing:
    image: ${HIVEMIND_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/hivemind}:${HIVEMIND_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - apps
      - hivemind
    networks:
      haf-network:
    command:
      - "sync"
      - "--database-url=postgresql://hivemind@haf/haf_block_log"
      - "--database-admin-url=postgresql://haf_admin@haf/haf_block_log"
      - "--test-max-block=100000"
    healthcheck:
      test: ["CMD-SHELL","/home/hivemind/block-processing-healthcheck.sh || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 72h
    # after requesting a shutdown with SIGTERM, allow the container 30 seconds to exit
    # before killing it.
    # Normally it will exit cleanly in a second or two, but it can take longer if it's
    # in the middle of massive sync.  When in massive sync, a forced shutdown can leave
    # the hivemind database in an inconsistent state, requiring an uninstall/reinstall
    # of hivemind to correct it.
    stop_grace_period: 30s
    stop_signal: SIGINT
    depends_on:
      haf:
        condition: service_healthy
      reputation-tracker-install:
        condition: service_completed_successfully
      hivemind-install:
        condition: service_completed_successfully

  hivemind-server:
    image: ${HIVEMIND_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/hivemind}:${HIVEMIND_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - legacy-hivemind-server
    networks:
      haf-network:
    command:
      - "--database-url=postgresql://hivemind@haf/haf_block_log"
      - "server"
    depends_on:
      hivemind-block-processing:
        condition: service_healthy
      haf:
        condition: service_healthy

  hivemind-postgrest-server:
    image: ${POSTGREST_IMAGE:-registry.gitlab.syncad.com/hive/haf_api_node/postgrest}:${POSTGREST_VERSION:-latest}
    profiles:
      - apps
      - hivemind
    networks:
      haf-network:
    environment:
      PGRST_ADMIN_SERVER_PORT: 3001
      PGRST_SERVER_PORT: 8080
      PGRST_DB_URI: "postgresql://hivemind@haf/haf_block_log?application_name=hive-mind-postgrest" # warning hivemind improperly matches all connections starting from `hivemind` and crashes if they are made externally (not from python)
      PGRST_DB_SCHEMA: hivemind_endpoints
      # PGRST_DB_ROOT_SPEC: home
      PGRST_DB_ANON_ROLE: hivemind
      PGRST_DB_POOL: 40
      PGRST_DB_POOL_ACQUISITION_TIMEOUT: 10
      PGRST_OPENAPI_MODE: "disabled" # unclear why this is set, I guess because we currently only support json-rpc?
      # when debugging, you can enable this
      # PGRST_DB_PLAN_ENABLED: true
    healthcheck:
      test: ["CMD-SHELL", "wget --timeout=2 -nv -t1 --spider 127.0.0.1:3001/ready || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 1m
    depends_on:
      hivemind-install:
        condition: service_completed_successfully
      haf:
        condition: service_healthy

  hivemind-postgrest-rewriter:
    image: ${HIVEMIND_REWRITER_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/hivemind/postgrest-rewriter}:${HIVEMIND_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - apps
      - hivemind
    healthcheck:
      test: ["CMD-SHELL", "wget --timeout=2 -nv -t1 --spider 127.0.0.1:81/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 1m
    depends_on:
      hivemind-postgrest-server:
        condition: service_healthy
    networks:
      - haf-network

  hivemind-uninstall:
    image: ${HIVEMIND_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/hivemind}:${HIVEMIND_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - hivemind-uninstall
    networks:
      haf-network:
    entrypoint:
      - /home/hivemind/app/uninstall_app.sh
    depends_on:
      haf:
        condition: service_healthy
    command:
      - "--postgres-url=postgresql://haf_admin@haf/haf_block_log"
