services:
  # run an ollama instance to compute vector embeddings.  
  # Without editing this config, your ollama instance will run entirely on CPU.
  # This is fine for embedding the query strings necessary for handling a low-to-moderate
  # volume of search API calls, but you will need GPU acceleration if you want to 
  # generate embeddings for posts.
  #
  # By default, we use a stripped-down ollama image that's fine for CPU embedding.
  # If you're using a GPU, you will likely need to switch to the official ollama image,
  # by setting OLLAMA_IMAGE=ollama/ollama in the .env file
  hivesense-ollama:
    image: ${OLLAMA_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/hivesense/ollama}:${OLLAMA_VERSION:-0.6.5}
    profiles:
      - hivesense
      - apps
      - ollama
    environment:
      - TZ=America/New_York
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=16
      - OLLAMA_NUM_THREADS=16
      - OLLAMA_KEEP_ALIVE=-1
      - OLLAMA_MODELS=/tmp/ollama
    tty: true
    networks:
      haf-network:
    volumes:
      - type: bind
        source: ${HAF_DATA_DIRECTORY:-${TOP_LEVEL_DATASET_MOUNTPOINT}}/ollama
        target: /tmp/ollama
    entrypoint: /bin/sh
    command: >
      -c "
        ollama serve &

        until ollama list > /dev/null 2>&1; do
          echo 'Waiting for ollama to start...'
          sleep 1
        done

        echo 'Pulling model...'
        ollama pull \${HIVESENSE_MODEL:-yxchia/multilingual-e5-base:F16}
        echo 'Ready.'

        wait
      "
    # uncomment for nvidia:
    ### runtime: nvidia
    # or uncomment for amd:
    ### image: ollama/ollama:0.7.0-rc1-rocm
    ### environment:
    ###  - HIP_VISIBLE_DEVICES=0
    ### devices:
    ###  - /dev/kfd
    ###  - /dev/dri
    ### group_add:
    ###  - video
  hivesense-install-schema:
    image: ${HIVESENSE_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/hivesense}:${HIVESENSE_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - hivesense
      - apps
      - hivesense-install
    environment:
      POSTGRES_HOST: haf
    command:
      - install_app
      - "--llm=${HIVESENSE_MODEL:-yxchia/multilingual-e5-base:F16}"
      - "--vector_size=${HIVESENSE_VECTOR_SIZE:-768}"
      - "--ollama=${HIVESENSE_OLLAMA:-http://haproxy:7012}"
      - "--start_block=${HIVESENSE_START_BLOCK:-1}"
      - "--parallel_workers=${HIVESENSE_WORKERS:-16}"
      - "--embedding_batch_size=${HIVESENSE_EMBEDDING_BATCH_SIZE:-100}"
      - "--tokenizer-model=${HIVESENSE_TOKENIZER_MODEL_NAME:-e5-base}"
      - "--tokens_per_chunk=${HIVESENSE_TOKENS_PER_CHUNK:-512}"
      - "--overlap_amount=${HIVESENSE_OVERLAP_AMOUNT:-0.15}"
      - "--use-halfvec-index=${HIVESENSE_USE_HALFVEC_INDEX:-TRUE}"
      - "--store-halfvec-embeddings=${HIVESENSE_STORE_HALFVEC_EMBEDDINGS:-TRUE}"
      - "--document-prefix=${HIVESENSE_DOCUMENT_PREFIX-passage: }"
      - "--query-prefix=${HIVESENSE_QUERY_PREFIX-query: }"
      - "--min-token-threshold=${HIVESENSE_MIN_TOKEN_THRESHOLD:-75}"
      - "--min-token-search-threshold=${HIVESENSE_MIN_TOKEN_SEARCH_THRESHOLD:-0}"
      - "--swagger-url=${PUBLIC_HOSTNAME}/"
      - "--use-reduced-embeddings=${HIVESENSE_USE_REDUCED_EMBEDDINGS:-false}"
      - "--reduced-matrix-json=/home/haf_admin/pca_projection_matrix.json"
      - "--reduced-dim=${HIVESENSE_REDUCED_DIMENSION:-128}"
      - "--hnsw-m=${HIVESENSE_HNSW_M:-16}"
      - "--hnsw-ef-construction=${HIVESENSE_HNSW_EF_CONSTRUCTION:-200}"
    volumes:
      - type: bind
        source: ${HIVESENSE_REDUCED_MATRIX_JSON:-/dev/null}
        target: /home/haf_admin/pca_projection_matrix.json
    networks:
      haf-network:
    depends_on:
      haf:
        condition: service_healthy
      hivemind-install:
        condition: service_completed_successfully
  # to uninstall Hivesense, shut down the stack and run a command like:
  #   docker compose --profile core --profile block-explorer-uninstall up -d
  hivesense-uninstall:
    image: ${HIVESENSE_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/hivesense}:${HIVESENSE_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - hivesense-uninstall
    environment:
      POSTGRES_HOST: haf
    command:
      - uninstall_app
    networks:
      haf-network:
    depends_on:
      haf:
        condition: service_healthy
  hivesense-postgrest-rewriter:
    image: ${HIVESENSE_REWRITER_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/hivesense/postgrest-rewriter}:${HIVESENSE_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - hivesense
      - apps
    healthcheck:
      test: ["CMD-SHELL", "wget --timeout=2 -nv -t1 --spider 127.0.0.1:81/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 1m
    init: true
    depends_on:
      hivesense-postgrest:
        condition: service_healthy
    networks:
      - haf-network
  hivesense-postgrest:
    image: ${POSTGREST_IMAGE:-registry.gitlab.syncad.com/hive/haf_api_node/postgrest}:${POSTGREST_VERSION:-latest}
    profiles:
      - hivesense
      - apps
    environment:
      PGRST_ADMIN_SERVER_PORT: 3001
      PGRST_DB_URI: postgresql://hivesense_user@haf/haf_block_log?application_name=hivesense_postgrest
      PGRST_DB_SCHEMA: hivesense_endpoints
      PGRST_DB_ANON_ROLE: hivesense_user
      PGRST_DB_POOL: 20
      PGRST_DB_POOL_ACQUISITION_TIMEOUT: 10
      PGRST_DB_ROOT_SPEC: root
      PGRST_DB_EXTRA_SEARCH_PATH: hivesense_app
    networks:
      haf-network:
    healthcheck:
      test: ["CMD-SHELL", "wget --timeout=2 -nv -t1 --spider 127.0.0.1:3001/ready || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 1m
    depends_on:
      hivesense-install-schema:
        condition: service_completed_successfully
      haf:
        condition: service_healthy
  hivesense-pca:
    image: ${HIVESENSE_SYNCER_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/hivesense/pca}:${HIVESENSE_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - hivesense-pca
    environment:
      POSTGRES_URI: postgresql://hivesense_owner@haf/haf_block_log?application_name=hivesense_pca
      #POSTGRES_URI: postgresql://hivesense_user@haf/haf_block_log?application_name=hivesense_pca
      SAMPLE_SIZE: ${HIVESENSE_PCA_SAMPLE_SIZE:-1000000}
      REDUCED_DIM: ${HIVESENSE_PCA_REDUCED_DIM:-128}
      PCA_MATRIX_PATH: output/pca_projection_matrix.npy
      BATCH_SIZE: 10000
    init: true
    tty: true
    stdin_open: true
    networks:
      haf-network:
        #command: ["python", "run_pca.py"]
        #command: ["python", "recall.py", "sample", "--num-queries", "100", "--output", "output/sample.json"]
        #command: ["python", "recall.py", "--table", "hivesense_app.posts_vectors", "search", "--topk", "20", "--queries", "output/sample.json", "--disable-index", "--parallel-workers", "16", "--output", "output/gt.json"]
    command: ["python", "recall.py", "--table", "hivesense_app.posts_vectors_reduced_128", "search", "--topk", "1000", "--queries", "output/sample.json", "--disable-index", "--parallel-workers", "16", "--output", "output/reduced_128.json"]
        #command: ["python", "recall.py", "analyze", "--gt", "output/gt.json", "--ann", "output/reduced_128.json", "-c", "25", "50", "75", "100", "500", "1000"]
        #command: ["python", "convert_embeddings.py", "--workers", "20"]
    volumes:
      - type: bind
        source: ${HAF_DATA_DIRECTORY:-${TOP_LEVEL_DATASET_MOUNTPOINT}}/hivesense-pca
        target: /app/output
    depends_on:
      hivesense-install-schema:
        condition: service_completed_successfully
      haf:
        condition: service_healthy
