services:
  hivemind-install:
    image: ${HIVEMIND_INSTANCE_IMAGE:-registry.gitlab.syncad.com/hive/hivemind/instance}:${HIVEMIND_INSTANCE_VERSION:-haf_api_node}
    profiles:
      - apps
      - hivemind
    networks:
      haf-network:
    command:
      - "setup"
      - "--database-admin-url=postgresql://haf_admin@haf/haf_block_log"
    depends_on:
      haf:
        condition: service_healthy

  hivemind-block-processing:
    image: ${HIVEMIND_INSTANCE_IMAGE:-registry.gitlab.syncad.com/hive/hivemind/instance}:${HIVEMIND_INSTANCE_VERSION:-haf_api_node}
    profiles:
      - apps
      - hivemind
    networks:
      haf-network:
    command:
      - "--database-url=postgresql://hivemind@haf/haf_block_log"
      - "sync"
    depends_on:
      hivemind-install:
        condition: service_completed_successfully

  hivemind-server:
    image: ${HIVEMIND_INSTANCE_IMAGE:-registry.gitlab.syncad.com/hive/hivemind/instance}:${HIVEMIND_INSTANCE_VERSION:-haf_api_node}
    profiles:
      - apps
      - hivemind
    networks:
      haf-network:
    command:
      - "--database-url=postgresql://hivemind@haf/haf_block_log"
      - "server"
    depends_on:
      hivemind-block-processing:
        condition: service_started

  hivemind-uninstall:
    image: ${HIVEMIND_INSTANCE_IMAGE:-registry.gitlab.syncad.com/hive/hivemind/instance}:${HIVEMIND_INSTANCE_VERSION:-haf_api_node}
    profiles:
      - hivemind-uninstall
    networks:
      haf-network:
    entrypoint:
      - /home/hivemind/app/uninstall_app.sh
    command:
      - "--postgres-url=postgresql://haf_admin@haf/haf_block_log"
