services:
  hivemind-rtracker-install:
    image: ${REPUTATION_TRACKER_REGISTRY:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/reputation_tracker}:${REPUTATION_TRACKER_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - hivemind
    environment:
      POSTGRES_HOST: haf
    networks:
      haf-network:
    command:
      - install_app
      - --is_forking=false
      - --is_attached=true
    depends_on:
      haf:
        condition: service_healthy
  hivemind-rtracker-uninstall:
    image: ${REPUTATION_TRACKER_REGISTRY:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/reputation_tracker}:${REPUTATION_TRACKER_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - reputation-tracker-uninstall
    environment:
      POSTGRES_HOST: haf
    networks:
      haf-network:
    command:
      - uninstall_app
    depends_on:
      haf:
        condition: service_healthy
  hivemind-rtracker-postgrest:
    image: ${POSTGREST_REGISTRY:-registry.gitlab.syncad.com/hive/haf_api_node/postgrest}:${POSTGREST_VERSION:-latest}
    profiles:
      - hivemind
    environment:
      PGRST_ADMIN_SERVER_PORT: 3001
      PGRST_DB_URI: postgresql://reptracker_user@haf/haf_block_log
      PGRST_DB_SCHEMA: reptracker_endpoints
      PGRST_DB_ANON_ROLE: reptracker_user
      PGRST_DB_POOL: 20
      PGRST_DB_POOL_ACQUISITION_TIMEOUT: 10
      PGRST_DB_EXTRA_SEARCH_PATH: reptracker_app
      # PGRST_OPENAPI_SERVER_PROXY_URI: http://${PUBLIC_HOSTNAME}/reptracker_user/
    healthcheck:
      test: ["CMD-SHELL", "wget --timeout=2 -nv -t1 --spider 127.0.0.1:3001/ready || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 1m
    networks:
      haf-network:
    depends_on:
      hivemind-rtracker-install:
        condition: service_completed_successfully
      haf:
        condition: service_healthy
  hivemind-rtracker-postgrest-rewriter:
    image: nginx
    profiles:
      - hivemind
    volumes:
      - type: bind
        source: hivemind_rtracker/hivemind_rtracker_nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: hivemind_rtracker/rewrite_rules.conf
        target: /etc/nginx/rewrite_rules.conf
        read_only: true
    depends_on:
      hivemind-rtracker-postgrest:
        condition: service_healthy
    networks:
      - haf-network
  semaphore:
    image: busybox
    depends_on:
      haf:
        condition: service_healthy
    command: ["sleep", "20"]
