services:
  jussi:
    image: registry.gitlab.syncad.com/hive/jussi:latest
    volumes:
      - type: bind
        source: ./jussi/config.json
        target: /home/jussi/config.json
        read_only: true
    command: --server_workers=4 --upstream_config_ifle=/home/jussi/config.json
