services:
  redis1:
    image: "redis:7.2-alpine"
    profiles:
      - servers
    networks:
      - haf-network
  redis2:
    image: "redis:7.2-alpine"
    profiles:
      - servers
    networks:
      - haf-network
  jussi:
    image: registry.gitlab.syncad.com/hive/jussi:latest
    profiles:
      - servers
        #environment:
        #  JUSSI_REDIS_URL: redis://redis1:6379
        #  JUSSI_REDIS_READ_REPLICA_URLS: redis://redis2:6379
    volumes:
      - type: bind
        source: ./jussi/config.json
        target: /home/jussi/config.json
        read_only: true
    command: --server_workers=4 --upstream_config_file=/home/jussi/config.json
    ports:
      - 9000:9000
    networks:
      - haf-network
  # to use our log analysis tools, we need to capture jussi traffic using a 
  # specific nginx logging config.  To do this, rename the actual jussi
  # service above to 'jussi-real', then uncomment the next section. 
  # jussi:
  #   image: nginx
  #   volumes:
  #     - type: bind
  #       source: ./jussi/nginx.conf
  #       target: /etc/nginx/nginx.conf
  #       read_only: true
  #     - type: bind
  #       source: ${HAF_LOG_DIRECTORY}/jussi
  #       target: /var/log/jussi
  #   ports:
  #     - 9000:80
  #   networks:
  #     - haf-network
