services:
  reputation-tracker-install:
    image: ${REPUTATION_TRACKER_REGISTRY:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/reputation_tracker}:${REPUTATION_TRACKER_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - apps
      - hafbe
      - hivemind
      - reputation-tracker-setup
    environment:
      POSTGRES_HOST: haf
    networks:
      haf-network:
    command:
      - install_app
      - --swagger-url=${PUBLIC_HOSTNAME}
    depends_on:
      haf:
        condition: service_healthy
  reputation-tracker-uninstall:
    image: ${REPUTATION_TRACKER_REGISTRY:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/reputation_tracker}:${REPUTATION_TRACKER_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - reputation-tracker-uninstall
    environment:
      POSTGRES_HOST: haf
    networks:
      haf-network:
    command:
      - uninstall_app
    depends_on:
      haf:
        condition: service_healthy
  reputation-tracker-block-processing:
    image: ${REPUTATION_TRACKER_REGISTRY:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/reputation_tracker}:${REPUTATION_TRACKER_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - apps
      - hafbe
      - hivemind
      - reputation-tracker-standalone
    environment:
      POSTGRES_HOST: haf
      POSTGRES_USER: reptracker_owner
    networks:
      haf-network:
    command:
      - process_blocks
    healthcheck:
      test: ["CMD-SHELL","/app/block-processing-healthcheck.sh"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 48h
    depends_on:
      reputation-tracker-install:
        condition: service_completed_successfully
      haf:
        condition: service_healthy
  reputation-tracker-postgrest:
    image: ${POSTGREST_REGISTRY:-registry.gitlab.syncad.com/hive/haf_api_node/postgrest}:${POSTGREST_VERSION:-latest}
    profiles:
      - apps
      - hivemind
      - reputation-tracker-standalone
      - hafbe
    environment:
      PGRST_ADMIN_SERVER_PORT: 3001
      PGRST_DB_URI: postgresql://reptracker_user@haf/haf_block_log
      PGRST_DB_SCHEMA: reptracker_endpoints
      PGRST_DB_ANON_ROLE: reptracker_user
      PGRST_DB_POOL: 20
      PGRST_DB_ROOT_SPEC: root
      PGRST_DB_POOL_ACQUISITION_TIMEOUT: 10
      PGRST_DB_EXTRA_SEARCH_PATH: reptracker_app
      # PGRST_OPENAPI_SERVER_PROXY_URI: http://${PUBLIC_HOSTNAME}/reptracker_user/
    healthcheck:
      test: ["CMD-SHELL", "wget --timeout=2 -nv -t1 --spider 127.0.0.1:3001/ready || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 1m
    networks:
      haf-network:
    depends_on:
      reputation-tracker-install:
        condition: service_completed_successfully
      haf:
        condition: service_healthy
  reputation-tracker-postgrest-rewriter:
    image: ${REPUTATION_TRACKER_REWRITER_REGISTRY:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/haf_block_explorer/postgrest-rewriter}:${REPUTATION_TRACKER_VERSION:-${HIVE_API_NODE_VERSION}}
    profiles:
      - apps
      - reputation-tracker-standalone
      - hafbe
      - hivemind
    depends_on:
      reputation-tracker-postgrest:
        condition: service_healthy
    networks:
      - haf-network
