services:
  swagger:
    image: swaggerapi/swagger-ui
    profiles:
      - hafbe
      - hivemind
      - hivesense
      - apps
    environment:
      URLS: >-
        [{url: "/hafbe-api/", name: "HAF Block Explorer"},
         {url: "/balance-api/", name: "Balance Tracker"},
         {url: "/reputation-api/", name: "Reputation Tracker"},
         {url: "/hivesense-api/", name: "Hivesense"},
         {url: "/hafah-api/", name: "HAfAH"},
         {url: "/hivemind-api/", name: "Hivemind"}]
    networks:
      haf-network:
    #healthcheck:
    #  test: ["CMD-SHELL","curl -f localhost:8080"]
