services:
  swagger:
    image: ${SWAGGER_IMAGE:-${HIVE_API_NODE_REGISTRY:-registry.hive.blog}/haf_api_node/swagger}:${SWAGGER_VERSION:-latest}
    profiles:
      - hafbe
      - hivemind
      - hivesense
      - apps
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      haf-network:
    healthcheck:
      test: ["CMD-SHELL","curl -sf localhost > /dev/null || exit 1"]
