services:
  varnish:
    image: varnish:7.6.1-alpine
    profiles:
      - servers
    volumes:
      - type: bind
        source: ./varnish/default.vcl
        target: /etc/varnish/default.vcl
        read_only: true
    tmpfs:
      - /var/lib/varnish/varnishd:exec
    environment:
      - VARNISH_SIZE=2G
    command:
      - -t 0
    depends_on:
      haproxy:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -T2 -nv -t1 --spider http://127.0.0.1/varnishcheck || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 1m
    networks:
      - haf-network
    # when varnish is run as a non-root user, it will run correctly the first time,
    # but fail with "Error: Cannot create test-file ..." after a restart.  See:
    #   https://github.com/varnish/docker-varnish/issues/53
    user: root
