services:
  varnish:
    image: varnish:7.3.0-alpine
    volumes:
      - type: bind
        source: ./varnish/default.vcl
        target: /etc/varnish/default.vcl
        read_only: true
    tmpfs:
      - /var/lib/varnish/varnishd:exec
    environment:
      - VARNISH_SIZE=2G
    networks:
      - haf-network
