server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "error"

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: container_scrape
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        # exclude containers
        regex: "/(prometheus|grafana|loki|promtail|node-exporter|cadvisor)"
        target_label: "container"
        action: drop
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container"
