{
 "title": "Blockstats",
 "tags": [ "blockchain" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Base data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "hived block number",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{apps=\"hived-pme\"} | json"
    }
   ]
  },
  {
   "title": "last irreversible block",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{apps=\"hived-pme\"} | json"
    }
   ]
  },
  {
   "title": "type of block_flow_control used with the block",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{apps=\"hived-pme\"} | json"
    }
   ]
  },
  {
   "title": "block id",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{apps=\"hived-pme\"} | json"
    }
   ]
  },
  {
   "title": "official timestamp of the block",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{apps=\"hived-pme\"} | json"
    }
   ]
  },
  {
   "title": "witness that signed the block",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{apps=\"hived-pme\"} | json"
    }
   ]
  },
  {
   "title": "Blocks in time",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "hived_pme_num_block{instance=\"hived-pme:9185\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  { "title": "Block stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "number of transactions contained in the block",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "hived_pme_txs{instance=\"hived-pme:9185\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "size of block in bytes (uncompressed)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hived_pme_size{instance=\"hived-pme:9185\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "offset from block timestamp (in microseconds) when the block was considered valid",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "hived_pme_offset{instance=\"hived-pme:9185\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Before - info on transactions that came to the node between this and previous block",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "number of all incoming transactions (API+P2P)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "hived_pme_before_inc{instance=\"hived-pme:9185\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "number of those accepted as valid",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "hived_pme_before_ok{instance=\"hived-pme:9185\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "number of failed due to authorization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "hived_pme_before_auth{instance=\"hived-pme:9185\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "number of failed due to lack of RC mana",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "hived_pme_before_rc{instance=\"hived-pme:9185\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "After - info on pending transactions that are reapplied during phase 2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }
  },
  {
   "title": "number of expired",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "hived_pme_after_exp{instance=\"hived-pme:9185\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "number of failed (for other reasons than expiration)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "hived_pme_after_fail{instance=\"hived-pme:9185\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "number of reapplied",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "hived_pme_after_appl{instance=\"hived-pme:9185\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "number of postponed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "hived_pme_after_post{instance=\"hived-pme:9185\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Exec - execution times (in microseconds)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 }
  },
  {
   "title": "offset from block timestamp when block was placed in the writer queue",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "hived_pme_exec_offset{instance=\"hived-pme:9185\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "how long block had to wait in writer queue before work started ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "hived_pme_exec_pre{instance=\"hived-pme:9185\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "time of actual work before the block was considered ready to be passed further",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "hived_pme_exec_work{instance=\"hived-pme:9185\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "time spend on further phase(s) after main work was done",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "hived_pme_exec_post{instance=\"hived-pme:9185\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "overall time spent by writer thread processing the block",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "hived_pme_exec_all{instance=\"hived-pme:9185\"}",
     "legendFormat": "{{role}}"
    }
   ]
  }
 ]
}