#!/bin/sh
set -eu

CFGDIR="/usr/local/etc/haproxy"
OVERLAY="$CFGDIR/20-email-alerts.cfg"

# nuke any stale overlay from previous runs
rm -f "$OVERLAY"

# Only create email overlay when HAPROXY_EMAIL_TO is set (opt-in)
if [ -n "${HAPROXY_EMAIL_TO:-}" ]; then
  FROM="${HAPROXY_EMAIL_FROM:-noreply@${PUBLIC_HOSTNAME:-localhost}}"
  LEVEL="${HAPROXY_EMAIL_LEVEL:-notice}"

  # Optional: ensure runtime dir exists; ignore errors if readonly/already present
  mkdir -p /run/haproxy 2>/dev/null || true

  cat > "$OVERLAY" <<EOF
# Auto-generated by entrypoint $(date -u +%FT%TZ)
# Email alerts via an unauthenticated local relay at smtp-relay:25
mailers mta
  mailer smtp smtp-relay:25

defaults
  email-alert from ${FROM}
  email-alert to ${HAPROXY_EMAIL_TO}
  email-alert mailers mta
  email-alert level ${LEVEL}
EOF
fi

# Run HAProxy. If args were provided, use them; otherwise use your normal defaults.
if [ "$#" -gt 0 ]; then
  exec haproxy "$@"
else
  exec haproxy -W -db -f "$CFGDIR"
fi
