#!/bin/sh
set -eu

CFGDIR="/usr/local/etc/haproxy"
OVERLAY="$CFGDIR/20-email-alerts.cfg"
LOGFILE="/var/log/haproxy/haproxy.log"

# Start syslogd if log directory is mounted (enables file logging)
# syslogd requires root to create /dev/log socket
if [ -d "$(dirname "$LOGFILE")" ] && [ "$(id -u)" = "0" ]; then
  touch "$LOGFILE" 2>/dev/null || true
  chown haproxy:haproxy "$LOGFILE" 2>/dev/null || true
  # -n = don't daemonize (but we background it)
  # -O = output to file
  # -S = smaller (no remote logging)
  syslogd -n -O "$LOGFILE" -S &
fi

# nuke any stale overlay from previous runs
rm -f "$OVERLAY"

# Only create email overlay when HAPROXY_EMAIL_TO is set (opt-in)
if [ -n "${HAPROXY_EMAIL_TO:-}" ]; then
  FROM="${HAPROXY_EMAIL_FROM:-noreply@${PUBLIC_HOSTNAME:-localhost}}"
  LEVEL="${HAPROXY_EMAIL_LEVEL:-notice}"

  mkdir -p /run/haproxy 2>/dev/null || true

  cat > "$OVERLAY" <<EOF
# Auto-generated by entrypoint $(date -u +%FT%TZ)
# Email alerts via an unauthenticated local relay at smtp-relay:25
mailers mta
  mailer smtp smtp-relay:25

defaults
  email-alert from ${FROM}
  email-alert to ${HAPROXY_EMAIL_TO}
  email-alert mailers mta
  email-alert level ${LEVEL}
EOF
fi

# Drop privileges and run HAProxy as haproxy user
if [ "$(id -u)" = "0" ]; then
  if [ "$#" -gt 0 ]; then
    exec su-exec haproxy haproxy "$@"
  else
    exec su-exec haproxy haproxy -W -db -f "$CFGDIR"
  fi
else
  # Already running as haproxy user
  if [ "$#" -gt 0 ]; then
    exec haproxy "$@"
  else
    exec haproxy -W -db -f "$CFGDIR"
  fi
fi
