#
# Homepage and endpoints of the API "HAF Block Explorer".
#
worker_processes  5;
error_log /dev/stdout info;
worker_rlimit_nofile 8192;

events {
  worker_connections 4096;
}
http {
    access_log /dev/stdout;
    server {
            listen 0.0.0.0:80 default_server;
            server_name _;

            location / {
                    # Default to an empty array
                    set $path_filters "{}";
                    # Can't find how to add brackets in other way.
                    set $open_bracket "{";
                    set $close_bracket "}";
                    # Match the first occurrence of path-filter
                    if ($args ~* "(^|&)path-filter=([^&]*)") {
                        set $path_filters "$2";
                    }
                    # Match the second occurrence of path-filter and concatenate it
                    if ($args ~* "(path-filter=[^&]*&)(path-filter=([^&]*))") {
                        set $path_filters "$path_filters,$3";
                    }
                    # Match the third occurrence of path-filter and concatenate it
                    if ($args ~* "(path-filter=[^&]*&){2}(path-filter=([^&]*))") {
                        set $path_filters "$path_filters,$4";
                    }
                    # Add the braces around the final $path_filters string if path_filters were found
                    if ($path_filters != "{}") {
                        set $path_filters "${open_bracket}${path_filters}${close_bracket}";
                    }
                    # Remove preaggregate path-filters
                    if ($args ~* "(^|&)(path-filter=[^&]*)") {
                        set $args $1;
                    }

                    include rewrite_rules.conf;
                    rewrite_log on;

                    proxy_pass  http://block-explorer-postgrest:3000;  # my PostREST is  here!

                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    #default_type;
                    proxy_hide_header Content-Location;
                    proxy_set_header  Connection "";
                    proxy_http_version 1.1;
            }
    }
}
