#!/bin/sh
set -eu

# Generate userlist.txt from environment variable
# With trust auth, the password is ignored but must be present
if [ -n "${PGBOUNCER_USERS:-}" ]; then
  : > /etc/pgbouncer/userlist.txt  # Create empty file
  # Convert space-separated list to quoted format with dummy password
  for user in $PGBOUNCER_USERS; do
    echo "\"$user\" \"trusted\"" >> /etc/pgbouncer/userlist.txt
  done
else
  # Default user list if not provided - dummy passwords for trust auth (password is ignored)
  cat > /etc/pgbouncer/userlist.txt <<EOF
"hafah_user" "trusted"
"hivemind_user" "trusted"
"hafbe_user" "trusted"
"btracker_user" "trusted"
"reptracker_user" "trusted"
"nfttracker_user" "trusted"
"hivesense_user" "trusted"
"stats" "trusted"
"postgres" "trusted"
"haf_admin" "trusted"
"pghero" "trusted"
"pgbouncer" "trusted"
EOF
fi

# Generate pgbouncer.ini
cat > /etc/pgbouncer/pgbouncer.ini <<EOF
;; PgBouncer configuration
;; Generated by docker-entrypoint.sh

[databases]
;; Main database - all users connect to the same physical database
haf_block_log = host=${PGBOUNCER_DB_HOST:-haf} port=${PGBOUNCER_DB_PORT:-5432} dbname=${PGBOUNCER_DB_NAME:-haf_block_log}

[pgbouncer]
;; Connection settings
listen_addr = 0.0.0.0
listen_port = 6432

;; Authentication
auth_type = trust
auth_file = /etc/pgbouncer/userlist.txt

;; Pool configuration
pool_mode = ${PGBOUNCER_POOL_MODE:-transaction}
default_pool_size = ${PGBOUNCER_DEFAULT_POOL_SIZE:-25}
reserve_pool_size = ${PGBOUNCER_RESERVE_POOL_SIZE:-5}
reserve_pool_timeout = ${PGBOUNCER_RESERVE_POOL_TIMEOUT:-3}
max_client_conn = ${PGBOUNCER_MAX_CLIENT_CONN:-200}
max_db_connections = ${PGBOUNCER_MAX_DB_CONNECTIONS:-30}

;; Timeouts
server_idle_timeout = ${PGBOUNCER_SERVER_IDLE_TIMEOUT:-600}
server_lifetime = ${PGBOUNCER_SERVER_LIFETIME:-3600}
server_reset_query = DISCARD ALL
server_check_delay = ${PGBOUNCER_SERVER_CHECK_DELAY:-30}
query_wait_timeout = ${PGBOUNCER_QUERY_WAIT_TIMEOUT:-120}
client_idle_timeout = ${PGBOUNCER_CLIENT_IDLE_TIMEOUT:-0}
client_login_timeout = ${PGBOUNCER_CLIENT_LOGIN_TIMEOUT:-60}

;; Low-level tuning
pkt_buf = ${PGBOUNCER_PKT_BUF:-4096}
tcp_keepalive = ${PGBOUNCER_TCP_KEEPALIVE:-1}
tcp_keepcnt = ${PGBOUNCER_TCP_KEEPCNT:-3}
tcp_keepidle = ${PGBOUNCER_TCP_KEEPIDLE:-60}
tcp_keepintvl = ${PGBOUNCER_TCP_KEEPINTVL:-10}

;; Logging
log_connections = ${PGBOUNCER_LOG_CONNECTIONS:-0}
log_disconnections = ${PGBOUNCER_LOG_DISCONNECTIONS:-0}
log_pooler_errors = 1
stats_period = ${PGBOUNCER_STATS_PERIOD:-60}

;; Admin settings
admin_users = pgbouncer
stats_users = pgbouncer, stats
EOF

echo "Starting PgBouncer with generated configuration..."
exec pgbouncer /etc/pgbouncer/pgbouncer.ini
