#!/bin/sh
set -eu

# Generate userlist.txt from environment variable
if [ -n "${PGBOUNCER_USERS_WITH_PASSWORDS:-}" ]; then
  : > /etc/pgbouncer/userlist.txt  # Create empty file

  # Parse comma-separated user:password pairs
  OLD_IFS="$IFS"
  IFS=','
  for user_pass in $PGBOUNCER_USERS_WITH_PASSWORDS; do
    # Extract user and password
    user=$(echo "$user_pass" | cut -d: -f1 | tr -d ' ')
    pass=$(echo "$user_pass" | cut -d: -f2-)  # Use -f2- to handle passwords with colons

    if [ "${PGBOUNCER_AUTH_TYPE:-trust}" = "md5" ]; then
      # Calculate MD5 hash: md5(password + username)
      hash=$(echo -n "${pass}${user}" | md5sum | cut -d' ' -f1)
      echo "\"$user\" \"md5${hash}\"" >> /etc/pgbouncer/userlist.txt
    else
      echo "\"$user\" \"trusted\"" >> /etc/pgbouncer/userlist.txt
    fi
  done
  IFS="$OLD_IFS"
elif [ -n "${PGBOUNCER_USERS:-}" ]; then
  : > /etc/pgbouncer/userlist.txt  # Create empty file
  # Backward compatibility: space-separated list without passwords
  for user in $PGBOUNCER_USERS; do
    if [ "${PGBOUNCER_AUTH_TYPE:-trust}" = "md5" ]; then
      # Without passwords, can't generate MD5 hashes
      echo "\"$user\" \"dummy\"" >> /etc/pgbouncer/userlist.txt
    else
      echo "\"$user\" \"trusted\"" >> /etc/pgbouncer/userlist.txt
    fi
  done
else
  # Default user list if not provided - dummy passwords for trust auth (password is ignored)
  cat > /etc/pgbouncer/userlist.txt <<EOF
"hafah_user" "trusted"
"hivemind_user" "trusted"
"hafbe_user" "trusted"
"btracker_user" "trusted"
"reptracker_user" "trusted"
"nfttracker_user" "trusted"
"hivesense_user" "trusted"
"stats" "trusted"
"postgres" "trusted"
"haf_admin" "trusted"
"pghero" "trusted"
"pgbouncer" "trusted"
EOF
fi

# Generate pgbouncer.ini
cat > /etc/pgbouncer/pgbouncer.ini <<EOF
;; PgBouncer configuration
;; Generated by docker-entrypoint.sh

[databases]
;; Main database - all users connect to the same physical database
haf_block_log = host=${PGBOUNCER_DB_HOST:-haf} port=${PGBOUNCER_DB_PORT:-5432} dbname=${PGBOUNCER_DB_NAME:-haf_block_log}

[pgbouncer]
;; Connection settings
listen_addr = ${PGBOUNCER_LISTEN_ADDR:-0.0.0.0}
listen_port = ${PGBOUNCER_LISTEN_PORT:-6432}

;; Authentication
auth_type = ${PGBOUNCER_AUTH_TYPE:-trust}
auth_file = /etc/pgbouncer/userlist.txt
EOF

cat >> /etc/pgbouncer/pgbouncer.ini <<EOF

;; Pool configuration
pool_mode = ${PGBOUNCER_POOL_MODE:-transaction}
default_pool_size = ${PGBOUNCER_DEFAULT_POOL_SIZE:-25}
reserve_pool_size = ${PGBOUNCER_RESERVE_POOL_SIZE:-5}
reserve_pool_timeout = ${PGBOUNCER_RESERVE_POOL_TIMEOUT:-3}
max_client_conn = ${PGBOUNCER_MAX_CLIENT_CONN:-200}
max_db_connections = ${PGBOUNCER_MAX_DB_CONNECTIONS:-30}

;; Timeouts
server_idle_timeout = ${PGBOUNCER_SERVER_IDLE_TIMEOUT:-600}
server_lifetime = ${PGBOUNCER_SERVER_LIFETIME:-3600}
server_reset_query = DISCARD ALL
server_check_delay = ${PGBOUNCER_SERVER_CHECK_DELAY:-30}
query_wait_timeout = ${PGBOUNCER_QUERY_WAIT_TIMEOUT:-120}
client_idle_timeout = ${PGBOUNCER_CLIENT_IDLE_TIMEOUT:-0}
client_login_timeout = ${PGBOUNCER_CLIENT_LOGIN_TIMEOUT:-60}

;; Low-level tuning
pkt_buf = ${PGBOUNCER_PKT_BUF:-4096}
tcp_keepalive = ${PGBOUNCER_TCP_KEEPALIVE:-1}
tcp_keepcnt = ${PGBOUNCER_TCP_KEEPCNT:-3}
tcp_keepidle = ${PGBOUNCER_TCP_KEEPIDLE:-60}
tcp_keepintvl = ${PGBOUNCER_TCP_KEEPINTVL:-10}
ignore_startup_parameters = ${PGBOUNCER_IGNORE_STARTUP_PARAMETERS:-extra_float_digits}

;; Logging
log_connections = ${PGBOUNCER_LOG_CONNECTIONS:-0}
log_disconnections = ${PGBOUNCER_LOG_DISCONNECTIONS:-0}
log_pooler_errors = 1
stats_period = ${PGBOUNCER_STATS_PERIOD:-60}

;; Admin settings
admin_users = pgbouncer
stats_users = pgbouncer, stats
EOF

echo "Starting PgBouncer with generated configuration..."
exec pgbouncer /etc/pgbouncer/pgbouncer.ini
