name: 'haf_api_node_dind'
services:
  docker:
    image: registry.gitlab.syncad.com/hive/haf_api_node/dind:${TAG:-latest}
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
      TINI_SUBREAPER: "true"
      TOP_LEVEL_DATASET_MOUNTPOINT: /cache/haf-datadir
    volumes:
      - type: volume
        source: docker-certs-ca
        target: /certs/ca
      - type: volume
        source: docker-certs-client
        target: /certs/client
      - type: volume
        source: docker-certs-server
        target: /certs/server
      - type: volume
        source: docker-lib
        target: /var/lib/docker
      - type: volume
        source: haf_datadir
        target: /cache/haf-datadir
    networks:
      - docker
volumes:
  docker-certs-ca:
  docker-certs-client:
    name: docker-certs-client
  docker-certs-server:
  docker-lib:
  haf_datadir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HAF_DATA_DIRECTORY}/
networks:
  docker:    
    name: docker