variables:
  API_NODE_VERSION: ${CI_COMMIT_SHORT_SHA}

.api-node-job:
  extends: .job-defaults
  variables:
    LAST_BLOCK_NUMBER: "5000000"
    ARGUMENTS: "--plugin database_api --replay-blockchain --stop-at-block ${LAST_BLOCK_NUMBER}"
    USE_ALTERNATE_HAPROXY_CONFIG: "true"
    PUBLIC_HOSTNAME: "dind"
    DOCKER_DRIVER: "overlay2"
    DOCKER_HOST: "tcp://${PUBLIC_HOSTNAME}:2376"
    DOCKER_TLS_SAN: "DNS:${PUBLIC_HOSTNAME}"
    CI_DEBUG_SERVICES: "false" # Change to true to debug services in this job
    GIT_STRATEGY: "none"
  image: 
    name: registry.gitlab.syncad.com/hive/haf_api_node/compose:${API_NODE_VERSION}
    entrypoint: [ "" ]
  services:
    - name: registry.gitlab.syncad.com/hive/haf_api_node/dind:${API_NODE_VERSION}
      alias: dind
      variables:
        HEALTHCHECK_TCP_PORT: '2376'

.haf-node-replay:
  extends: .api-node-job
  timeout: 2 hours
  variables:
    TOP_LEVEL_DATASET_MOUNTPOINT: "${REPLAY_DIRECTORY}"
    HAF_DB_URL: "postgresql://hivemind@haf/haf_block_log"
    PSQL_COMMAND: "SELECT current_block_num FROM hive.contexts WHERE name = 'hivemind_app'"
  script:
    - docker-entrypoint.sh /haf-api-node/ci/scripts/replay-api-node.sh
  after_script:
    - docker-entrypoint.sh /haf-api-node/ci/scripts/after-script.sh
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - "*.txt"
      - "*.log"
      - "logs/"
      - "*.json"

.haf_api_node_replay_data_copy:
  extends: .job-defaults
  image: 
    name: registry.gitlab.syncad.com/hive/haf_api_node/compose:${API_NODE_VERSION}
    entrypoint: [ "" ]
  script:
    - /haf-api-node/ci/scripts/copy-datadir.sh

.haf_api_node_test:
  extends: .api-node-job
  variables:
    TOP_LEVEL_DATASET_MOUNTPOINT: "${REPLAY_PIPELINE_DIRECTORY}"
    FF_NETWORK_PER_BUILD: "true"
  services:
    - !reference [.api-node-job, services]
    - name: registry.gitlab.syncad.com/hive/haf_api_node/compose:${API_NODE_VERSION}
  script:
    - docker-entrypoint.sh /haf-api-node/ci/scripts/test-api-node.sh
  after_script:
    - docker-entrypoint.sh /haf-api-node/ci/scripts/after-script.sh
  artifacts:
    when: always
    expire_in: 1 week
    paths: # Must include paths from .haf-node-replay, !reference doesn't work
      - "*.txt"
      - "*.log"
      - "logs/"
      - "*.json"